### ISSUE TITLE
Alpaca Adjusted Prices

### ISSUE THREAD

**Issue by Algo-Mike** [kzhdev/alpaca_zorro_plugin#11]
Hi Kun,

Thanks for creating this very useful plugin!

Currently, the Zorro Trader Download.c script, in conjunction with your Alpaca plugin, downloads **unadjusted** 1 minute prices. Stock splits look like huge drops in price which create all kinds of issues with backtesting. Alpaca does offer adjusted prices, as per this Python script, run on my paper account:

def get_bars(symbol, start, end, limit=1000, timeframe='1Min', adjustment = 'raw'):
    base_url = f'[https://data.alpaca.markets/v2/stocks/{symbol}/bars](https://data.alpaca.markets/v2/stocks/%7Bsymbol%7D/bars)'
    request_headers = {'APCA-API-KEY-ID': 'Paper-account-key',
                        'APCA-API-SECRET-KEY' : 'Paper-account-secret'}
    request_params = {'start' : start, 'end' : end, 'limit' : limit, 'timeframe' : timeframe, 'adjustment' : adjustment}
    return requests.get(base_url, params=request_params, headers=request_headers).json()

bars = get_bars('AAPL', '2020-08-27', '2020-09-01', adjustment='raw')['bars']
print(bars)
bars = get_bars('AAPL', '2020-08-27', '2020-09-01', adjustment='all')['bars']
print(bars)

The result for a stock split, on split day (AAPL): 
Apple UNADJUSTED:
[{'c': 507, 'h': 507, 'l': 506.1, 'n': 71, 'o': 506.1, 't': '2020-08-24T08:00:00Z', 'v': 5941, 'vw': 506.505578},
...
{'c': 506.1, 'h': 506.1, 'l': 505.74, 'n': 145, 'o': 505.75, 't': '2020-08-24T23:59:00Z', 'v': 9248, 'vw': 505.959286}]

Apple ADJUSTED:
[{'c': 124.01, 'h': 124.01, 'l': 123.79, 'n': 71, 'o': 123.79, 't': '2020-08-24T08:00:00Z', 'v': 23764, 'vw': 123.89},
...
{'c': 123.79, 'h': 123.79, 'l': 123.7, 'n': 145, 'o': 123.7, 't': '2020-08-24T23:59:00Z', 'v': 36992, 'vw': 123.75}]

What did the trick here is to add the **adjustment** parameter and set it to **'all'** (adjustment for splits and dividends).

How can I do the same with your Alpaca Zorro plugin? I tried adding brokerCommand(SET_ORDERTEXT, "adjustment = 'all"); to the Download.c script, with no luck. I guess it only works with orders, not downloading data. The log message was "2024-04-28 16:58:21 | DEBUG | Unhandled command: 47 0."

Please advise.

Thank you in advance,
Algo Mike

**Comment by kzhdev** [comment]
@Algo-Mike Sorry, I just saw this issue. I don't know why I didn't get any notification. I do have a version that downloads adjusted market data by default. I can create a new release shortly.

**Comment by Algo-Mike** [comment]
That would be great, thank you!

**Comment by kzhdev** [comment]
1.3.0 is released. By default, the adjustment is set to all. You can change the adjustment via brokerCommand as following:

  ``` C++
  #include <AlpacaBrokerCommands.h>
  ....
  brokerCommand(SET_ADJUSTMENT, ADJUSTMENT_RAW);

  // Valid Adjustment values are
  //  ADJUSTMENT_RAW      - 0
  //  ADJUSTMENT_SPLIT    - 1
  //  ADJUSTMENT_DEVEDEND - 2
  //  ADJUSTMENT_ALL      - 3
  ```

**Comment by Algo-Mike** [comment]
Hi Kun, and thank you for the very fast resolution! I downloaded v1.3.0 but unfortunately it does not work for me. Here's what I am getting when running the Zorro Trader Download.c script:
-----
Download compiling............ ok

Download...
Login 0 Alpaca..
!Use Alpaca Basic Market Data..
!auth failed (402).
!Websocket disconnected
!Unable to open Alpaca websocket. Prices will be pulled from REST API.
!Account PA3FUH6WLTO3 at UTC 05-20 00:17
!NVDA 12-31 23:01:00 to 12-31 23:59:59 failed
!NVDA 12-31 23:01:00 to 12-31 23:58:59 failed
Error 035: NVDA download 5 errors.
-----
Now, please note the account that is being used: PA3FUH6WLTO3
This is NOT my paper trading account. I tried reset the API account and key 3 times, but it still does not work. It keeps using this PA3FUH6WLTO3 account no matter what I put into the Zorro Trader Login/password fields.

Please advise. Thanks!

**Comment by kzhdev** [comment]
PA3FUH6WLTO3 is your account number, it's not the API key. You should see the number on the Alpaca website.
`!Account PA3FUH6WLTO3 at UTC 05-20 00:17` means you are successfully logged in.

Although the WebSocket failed to connect, it switched to the RESI API. 

`Error 035: NVDA download 5 errors. ` The error is due to there is no bars in the time range.

Please try to delete the NVDA .t6 file in your Historical folder then try again.

**Comment by Algo-Mike** [comment]
You are correct about the account number, I thought it was the key. Anyway, I reset the paper account again and now, with the new Key and Secret, it seems to work. I am currently downloading some historical prices. Will circle back here if there are any more issues.

**Comment by kzhdev** [comment]
Okay, the sandbox WebSocket (wss://stream.data.sandbox.alpaca.markets/{version}/{feed}) does not work. That's why the authentication failed.

I rolled back the change. Please use v1.3.1.

**Comment by Algo-Mike** [comment]
Excellent, thank you! BTW, I did NOT use the account number as the Key :-) It appeared in the error message, though, so I thought it may be relevant. Also, two observations. v1.2.1 was downloading unadjusted prices delayed 15-30 mins (I think) so I could get all historical data until "today" during evening hours. v1.3.0 does download adjusted prices indeed, but does not download anything past 2023. I will try v1.3.1 and my python scripts tomorrow and circle back here with the results. 

Thank you very much for your help!

**Comment by kzhdev** [comment]
Need to set the feed to IEX specifically for the Free market data plan. Please try 1.3.2.

**Comment by Algo-Mike** [comment]
I tried both 1.3.1 and 1.3.2. Here's what I got:

With 1.3.1 you can only download historical data from 2016 to 2023. 2024 won't download.
With 1.3.2 you can only download historical data from 2020 to yesterday, but nothing past 2020.

My python script (above) downloads everything from 2016 to yesterday. This is the behavior I would like to see.
Also, I glanced over the alpaca_market_data.h source file. For downloading historical data, can you just use this url:
https://data.alpaca.markets/v2/stocks/{symbol}/bars ? Please note that this does not require to specify IEX data.

Thank you!

**Comment by kzhdev** [comment]
Hmm, for the Free plan, the feed prevented me from downloading 2024 data when I tried this morning.

2024-05-20 09:56:04 | TRACE | --> https://data.alpaca.markets/v2/stocks/NVDA/bars?start=2024-01-01T00:00:00Z&end=2024-05-20T14:56:04Z&limit=10000&timeframe=1Min&sort=desc&adjustment=all
2024-05-20 09:56:04 | TRACE | <-- {"message":"subscription does not permit querying recent SIP data"}

However, it is OK to download data from the early years without setting the feed to IEX. 

I can run more tests tomorrow.

**Comment by kzhdev** [comment]
I removed the IEX feed and adjusted the end time for the free plan.

Please try: https://github.com/kzhdev/alpaca_zorro_plugin/releases/download/v1.3.3/AlpacaZorroPlugin_v1.3.3.zip

**Comment by Algo-Mike** [comment]
I'm getting a "Not found" error.

**Comment by kzhdev** [comment]
[AlpacaZorroPlugin_v1.3.3.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15396345/AlpacaZorroPlugin_v1.3.3.zip)

**Comment by Algo-Mike** [comment]
Thank you very much! Downloading historical data works fine, with websockets disabled. The data is adjusted, and I am able to download from 2016 to yesterday. Tomorrow during market hours I will play with the websocket functionality.

Much appreciated!

**Comment by Algo-Mike** [comment]
Here's another kind of error message I'm getting:

!Subscribe ANET
Error 054: ANET invalid asset price

**Comment by kzhdev** [comment]
Can you enable logging by adding the following in the ZorroFix.ini file and send me the Alpaca log tomorrow?
`
AlpacaLogLevel = 5
AlpacaLogType = 88
`

**Comment by kzhdev** [comment]
Please use the WebSocketProxy from the 1.3.3 release.

**Comment by kzhdev** [comment]
A correction, please use AlpacaLogType = 96.

**Comment by Algo-Mike** [comment]
All right, I ran this according to your instructions several times today. The result was the same every time. Here's what Zorro Trader displays:

!Subscribe ADBE.
!Subscribe ADI
!Subscribe ADP.
!Subscribe ANET.
!Subscribe ATHM.
!Subscribe CALM
!Subscribe COR
!Subscribe CTVA.
!Subscribe FNV.
!Failed to subscribe FNV from Websocket. Price will be polled from REST API.
Error 042: no FNV parameters
!Subscribe FSLR.
!Failed to subscribe FSLR from Websocket. Price will be polled from REST API.
Error 042: no FSLR parameters
!Subscribe MNST.
!Failed to subscribe MNST from Websocket. Price will be polled from REST API...
!Subscribe MRNA.
!Failed to subscribe MRNA from Websocket. Price will be polled from REST API...
!Subscribe MRO
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests..
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.
!Failed to get lastQuotes for A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA error: too many requests.

I am attaching the logfiles as well.
[Alpaca_2024-05-23_135519.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15420778/Alpaca_2024-05-23_135519.log)
[WebsocketProxy.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15420782/WebsocketProxy.log)

**Comment by kzhdev** [comment]
@Algo-Mike Thanks for the logging.

`2024-05-23 12:57:31 | TRACE | [{"T":"error","code":405,"msg":"symbol limit exceeded"}]`

Unfortunately, the Free plan has a 30-symbol limit. That is the reason for the WebSocket subscription failure. Please refer to doc: https://alpaca.markets/deprecated/docs/api-documentation/api-v2/market-data/alpaca-data-api-v2/real-time/ 

Please disable the WebSocket by adding `AlpacaUseWebsocket = 0` in the ZorroFix.ini file.

Another issue is that the request rate exceeded Alpaca's 200-per-second limit for the Free plan. I set the GET_MAXREQUESTS for the Free plan in the plugin to 200, but Zorro doesn't control the request rate accordingly. What is your BarPeriod? Consider lowering it or adding `MaxRequests = 100;` to reduce the request rate in your Zorro script.

**Comment by Algo-Mike** [comment]
The number of symbols in my Assets list is 29, precisely because the limit is 30. My BarPeriod = 10 min, I cannot lower it or the script won't work. Not sure why the script would send 200 requests per second, as there are only 29 symbols. Even if it queries every minute, it doesn't add up. I will try disabling the websocket and using MaxRequests =100; tomorrow, and also play with a python script that will subscribe the 29 symbols via alpaca-api. Thank you!

**Comment by kzhdev** [comment]
![image](https://github.com/kzhdev/alpaca_zorro_plugin/assets/1855243/3c668f34-902b-42f7-a875-2ee4333faf77)

The subscription failed after successfully subscribing to 15 symbols. It appears that the 30-symbol limit includes both quotes and trades.

**Comment by Algo-Mike** [comment]
I did a little Python testing today. Here's the code:
---
import time
from alpaca.data.live import StockDataStream

stream = StockDataStream("PKCO8L6W20UDOX0KEYVC", "OckPntejQAQdqipxKvx8hCPAnHbwE6LR34EvNBxb")

async def handle_bars(data):
  print(data)
  print("BARS")
  time.sleep(1)

async def handle_quotes(data):
  print(data)
  print("QUOTES")

stream.subscribe_bars(handle_bars, "AAPL", "MSFT","NVDA","TSLA", "MSFT", "AMZN", "GOOGL", "FB", "BRK.B", "JPM", "JNJ", "V", "WMT", "PG", "UNH", "HD", "BAC", "VZ", "CVX", "KO", "DIS", "MCD", "INTC", "PEP", "ABT","ABBV","ACN","ADBE","ADI","ADP") #,"ADSK")

stream.subscribe_quotes(handle_quotes, "AAPL", "MSFT","NVDA","TSLA", "MSFT", "AMZN", "GOOGL", "FB", "BRK.B", "JPM", "JNJ", "V", "WMT", "PG", "UNH", "HD", "BAC", "VZ", "CVX", "KO", "DIS", "MCD", "INTC", "PEP", "ABT","ABBV","ACN","ADBE","ADI","ADP") #,"ADSK")

stream.run()
---
We are receiving both bars and quotes for 30 assets with no issues. Adding the #commented_out asset at the end triggers a limit error. This script ran for about an hour with no issues, and I stopped it to try the next one.

**Comment by Algo-Mike** [comment]
I tested with Zorro Trader with 14 assets in AssetFix.csv, which is less than 15 (above). Reducing the number of assets eliminates the !Subscribe issue. Setting MaxRequest = 0.1 (minimum) seems to make a difference.

However, there are still many other errors. like:

!Subscribe FNV
Error 42: no FNV parameters

Lookback 400 bars, 2024-05-24..(NaD)
Warning 033: no FSLR data in INITRUN
Warning 033: no MRO data in INITRUN
Warning 033: no NUE data in INITRUN
Warning 033: no NXT data in INITRUN......
Warning 035: FSLR gap at #16 (NaD) 0->0.00000
Warning 035: FSLR gap at #16 (NaD) 0->0.00000
Warning 035: FSLR gap at #16 (NaD) 0->0.00000.
Warning 035: MRO gap at #16 (NaD) 0->0.00000.........

I am attaching the log files as well. Hope this helps!
[Alpaca_2024-05-24_143332.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15438909/Alpaca_2024-05-24_143332.log)

[WebsocketProxy.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15438922/WebsocketProxy.log)

**Comment by kzhdev** [comment]
Thanks for doing the Python test. The plugin subscribes to trades in case the script sets the PRICE_TYPE to trade. I can change it to subscribe to trades after the script sets the PRICE_TYPE to trade.

The log you attached still has "too many requests" errors. I can add throttle to the request.

**Comment by Algo-Mike** [comment]
It would be great if we could use the 30 symbols limit, and throttle the requests. Thank you!

**Comment by kzhdev** [comment]
Please try this 
[AlpacaZorroPlugin_v.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15463238/AlpacaZorroPlugin_v.zip)

**Comment by Algo-Mike** [comment]
Unfortunately, it's not much better. Lots of invalid asset price errors:

!Subscribe NXT
Error 054: NXT invalid asset price
!Subscribe SGML
Error 054: SGML invalid asset price

and too many requests:

Error 054: NXT invalid asset price
!Failed to get lastQuotes for FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA,A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,GOOG,FIS error: too many requests.
!Failed to get lastQuotes for FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA,A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,GOOG,FIS error: too many requests.
Error 054: AAP invalid asset price
!Failed to get lastQuotes for FNV,FSLR,MNST,MRNA,MRO,MSFT,NUE,NVDA,NXT,SGML,TSLA,WPM,SPY,DIA,A,ABBV,AAL,AAP,AAPL,ACGL,ACN,ADBE,ADI,ADP,ANET,ATHM,CALM,COR,CTVA,GOOG,FIS error: too many requests.

The too many requests issue is resolved by using MaxRequests = 0.1;

However, the rest of the errors remain. I am attaching the logs. Thanks!
[Alpaca_2024-05-28_135354.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15474098/Alpaca_2024-05-28_135354.log)
[WebsocketProxy.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15474100/WebsocketProxy.log)

**Comment by Algo-Mike** [comment]
Also, it never gets data for the symbol FNV. I checked, Alpaca has it. The entry in the Assets.csv is also incorrect.

**Comment by kzhdev** [comment]
Some of your symbols are less liquid, such as FSLR, SGML, NXT, FNV, etc. NXT had only 1 quote through WebSocket, and the others didn't have any quote updates from WebSocket at all. No quote update from WebSocket caused the plugin to keep getting from the REST API which in turn breached the request rate limit.

We can make a change to only query REST API once and rely on WebSoket for the new quote update.

**Comment by kzhdev** [comment]
Please try this one. I added the fix to prevent the plugin from continuously fetching quotes from the REST AIP and implemented a robust global throttle.

[AlpacaZorroPlugin_v.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15483851/AlpacaZorroPlugin_v.zip)

**Comment by kzhdev** [comment]
[AlpacaZorroPlugin_v.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15485155/AlpacaZorroPlugin_v.zip)

According to Zorro's suggestion, the price and spread should not be set if the ASK price is 0. This should get rid of the 054 error.

**Comment by Algo-Mike** [comment]
Works great! 054 is gone, as are most the other errors. The only one that pops every now and the is:

!Subscribe AAP
Load AAP prices..
Error 035: AAP download 5 errors 30800+890 min, gap 19 min

Other than this kind of error, nothing else to report. I will keep testing tomorrow, and circle back with the results.

Thank you very much!

**Comment by Algo-Mike** [comment]
I just tried to download some data with the Download.c script. Worked fine with the previous version. Now it does not work. I am attaching the logs. 

[WebsocketProxy.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15492165/WebsocketProxy.log)
[Alpaca_2024-05-29_204724.log](https://github.com/kzhdev/alpaca_zorro_plugin/files/15492168/Alpaca_2024-05-29_204724.log)

**Comment by Algo-Mike** [comment]
Download compiling............ ok

Download...
Login 0 Alpaca..
!Use Alpaca Basic Market Data..
!Account PA3FUH6WLTO3 at UTC 05-30 00:47..........
!Failed to get bars. Brokerprogress returned zero. Aborting...
!A 05-30 00:01:00 to 05-30 00:47:36 failed.
Logout.. ok
Time 00:02:12

**Comment by kzhdev** [comment]
[AlpacaZorroPlugin_v.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15492416/AlpacaZorroPlugin_v.zip)
Fixed the issue.

**Comment by kzhdev** [comment]
[AlpacaZorroPlugin_v.zip](https://github.com/kzhdev/alpaca_zorro_plugin/files/15492431/AlpacaZorroPlugin_v.zip)
Fixed the issue.

**Comment by Algo-Mike** [comment]
After two full days of algo trading during market hours and downloading historical data outside of market hours, it appears everything is running smoothly. I will do some more historical data downloads during the week-end and circle back here. Thank you for updating the plugin!

**Comment by kzhdev** [comment]
Thank you for helping to test the plugin. I do add a minor fix. I will keep testing the plugin for a day or two.

**Comment by Algo-Mike** [comment]
I had some issues today. Here's the Zorro output:

!order not found for ZORRO_415500013
!order not found for ZORRO_415500013
!order not found for ZORRO_415500013
!order not found for ZORRO_415500004
!order not found for ZORRO_415500004
!order not found for ZORRO_415500006.
!order not found for ZORRO_415500009
!order not found for ZORRO_415500013
!order not found for ZORRO_415500009
!order not found for ZORRO_415500012
!order not found for ZORRO_415500006
!order not found for ZORRO_415500013

I am attaching the Alpaca log. Can't upload the websocket log as the file is huge.
[Alpaca_2024-06-05_102659.zip](https://github.com/user-attachments/files/15594890/Alpaca_2024-06-05_102659.zip)

**Comment by Algo-Mike** [comment]
Also, I would like to test the version you are currently testing, but you didn't post the link. Please advise. Thank you for your effort!

**Comment by Algo-Mike** [comment]
I managed to get uploadable logs for the "order not found" issue:

[Alpaca_2024-06-05_143133.log](https://github.com/user-attachments/files/15595577/Alpaca_2024-06-05_143133.log)
[WebsocketProxy.log](https://github.com/user-attachments/files/15595579/WebsocketProxy.log)

Hope this helps.

**Comment by Algo-Mike** [comment]
Well, it seems an order got through, but still lots of errors:

!order not found for ZORRO_415500013
!order not found for ZORRO_415500009
!order not found for ZORRO_415500006

[Wed 24-06-05 20:00] 30006 +22.10 5/5 (75.98)
[ADBE::L00007] Trail 1@455.66 Stop 420.18
!order not found for ZORRO_415500006
!order not found for ZORRO_415500009
!order not found for ZORRO_415500009....................................................

[Wed 24-06-05 20:10] 30006 +22.19 5/5 (75.98).
[ADBE::L00007] Trail 1@455.66 Stop 424.19.

**Comment by kzhdev** [comment]
This error is not related to websocket at all.

Please run following in the terminal/cmd, search for "client_order_id":"ZORRO_4115000xx" in the return. Do you find those orders?

curl -X GET -H "APCA-API-KEY-ID: xxxx" -H "APCA-API-SECRET-KEY:xxxx" https://api.alpaca.markets/v2/orders?status=all

Here is the version I'm testing:
[AlpacaZorroPlugin_v.zip](https://github.com/user-attachments/files/15596526/AlpacaZorroPlugin_v.zip)

**Comment by kzhdev** [comment]
You need to replace the xxxx with your alpaca's API KEY and SERET in the above command.

**Comment by kzhdev** [comment]
Please change the "AlpacaLogType" to 8 in the ZorroFix.ini. It will log order responses.

**Comment by kzhdev** [comment]
Sorry, the above version is not good. Try this one:

[AlpacaZorroPlugin_v.zip](https://github.com/user-attachments/files/15600986/AlpacaZorroPlugin_v.zip)

**Comment by Algo-Mike** [comment]
This last version (above) worked great during trading hours today. No issues to report. Will circle back tomorrow.

**Comment by Algo-Mike** [comment]
Actually, I just tried to download minute data for today. It kind of works, but I'm getting the too many requests again.

!Failed to get bars. too many requests.
Error 035: DECK download 5 errors 167 min
Load DFS 2024..
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: DFS download 5 errors 365 min
Load DG 2024..
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: DG download 5 errors 395 min

**Comment by Algo-Mike** [comment]
Also, I can't download any historical data before 2024. This used to work, but now it doesn't.

**Comment by kzhdev** [comment]
I tried downloading minute data but didn't see "too many requests." Do you have multiple Zorro running at the same time? If you use the Free market data plan, do you have "AlpacaPaidDataPlan = 0" in the ZorroFix.ini file?

**Comment by Algo-Mike** [comment]
I am still getting it, although today not as often. I do not have multiple Zorro instances running at the same time. The flag is set to 0, as it always was. The max requests flag is set as well.

!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: ZBH download 5 errors 370 min
Load ZBRA 2024..
!Failed to get bars. too many requests.
!Failed to get bars. too many requests..
Error 035: ZBRA download 5 errors 171 min
Load ZTS 2024..
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: ZTS download 5 errors 387 min

**Comment by kzhdev** [comment]
Could you set the AlpacaLogType = 56 and update the logs?

**Comment by Algo-Mike** [comment]
Sure. Here's what I get:

!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: ZBH download 5 errors 1158 min
Load ZBRA 2024...
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
!Failed to get bars. too many requests.
Error 035: ZBRA download 5 errors 552 min
!Failed to get bars. too many requests.
Load ZTS 2024..
!Failed to get bars. too many requests.
Error 035: ZTS download 5 errors 1154 min

[Alpaca_2024-06-13_193248.log](https://github.com/user-attachments/files/15830633/Alpaca_2024-06-13_193248.log)
[WebsocketProxy.log](https://github.com/user-attachments/files/15830635/WebsocketProxy.log)

**Comment by kzhdev** [comment]
Thanks for the log. I suspect the error was in the get bars response JSON, but I don't see the responses logged. Please make sure you set AlpacaLogLevel = 5 and AlpacaLogType = 56.

Are you using Zorro's Download scripts? Can you give me your Asset list? I will try to reproduce the issue.

**Comment by Algo-Mike** [comment]
The problem persists. I set everything as you asked. The script is Download.c with MaxRequests = .1; The asset list is the whole SP500. I am attaching it, and the logs. There is only one instance of Zorro running.

[Alpaca_2024-06-17_205206.log](https://github.com/user-attachments/files/15879184/Alpaca_2024-06-17_205206.log)
[WebsocketProxy.log](https://github.com/user-attachments/files/15879188/WebsocketProxy.log)
[AssetsSP500.csv](https://github.com/user-attachments/files/15879192/AssetsSP500.csv)

**Comment by kzhdev** [comment]
Please try the attached dll.
[AlpacaZorroPlugin_v.zip](https://github.com/user-attachments/files/15919071/AlpacaZorroPlugin_v.zip)

**Comment by kzhdev** [comment]
@Algo-Mike Do you still see the "too many requests" error?

**Comment by Algo-Mike** [comment]
Have been testing for a few days now, both downloading and paper trading. I didn't get the "too many requests" error anymore. Will keep testing and circle back here.
