### ISSUE TITLE
Limit orders not working

### ISSUE THREAD

**Issue by degloff** [kzhdev/alpaca_zorro_plugin#12]
Resting limit orders (i.e. posted to NOT aggressing) are not working. 

Setup: Zorro 2.61.4b

To see the problem run this script

```
#include <stdio.h>
#include <default.c>
#include <profile.c>

#define ORDERTYPE_GTC 2

var round_up(var in, var multiple) {
	var m = fmod(in, multiple);
	if (m == 0.0) {
		return in;
	}
	else {
		var down = in - m;
		return down + ifelse(in < 0.0, -multiple, multiple);
	}
}

var round_down(var in, var multiple) {
	return in - fmod(in, multiple);
}

void diagnostics_tmf() {
	var Close = priceClose();
	var TopAsk = Close;
	var TopBid = Close - Spread;
	printf("\ntmf [%s] id=%d %s missed=%s pending=%s open=%s unfilled=%s TradePriceOpen=%.5f TradePriceClose=%.5f TradeFill=%.5f TradeProfit=%.5f",
		strdate("%H:%M:%S.", NOW),
		TradeID,
		ifelse(TradeIsLong, "buy", "sell"),
		ifelse(TradeIsMissed, "yes", "no"),
		ifelse(TradeIsPending, "yes", "no"),
		ifelse(TradeIsOpen, "yes", "no"),
		ifelse(TradeIsUnfilled, "yes", "no"),
		TradePriceOpen,
		TradePriceClose,
		TradeFill,
		TradeProfit
	);

	return 0;
}

void diagnostics_trades() {
	for (open_trades)
	{
		printf("\n+++++ %d %s %s TradeLots(open)=%.6f TradeLotsTarget=%.6f TradePriceOpen=%.6f TradeProfit=%.6f",
			TradeID,
			ifelse(TradeIsOpen, "open", "pending"),
			ifelse(TradeIsLong, "buy", "sell"),
			(var)TradeLots,
			(var)TradeLotsTarget,
			(var)TradePriceOpen,
			(var)TradeProfit);
	}

	for (closed_trades)
	{
		printf("\n+++++ %d %s %s TradeLots(open)=%.6f TradeLotsTarget=%.6f TradePriceOpen=%.6f TradePriceClose=%.6f TradeProfit=%.6f",
			TradeID,
			ifelse(TradeIsOpen, "closed", "pending"),
			ifelse(TradeIsLong, "buy", "sell"),
			(var)TradeLots,
			(var)TradeLotsTarget,
			(var)TradePriceOpen,
			(var)TradePriceClose,
			(var)TradeProfit);
	}
}

static var startTime;
static bool Quoting = false;
static bool Inventory = false;
static int count = 0;
TRADE* BidTrade;
TRADE* AskTrade;

void tick() 
{
	if (is(LOOKBACK)) return;
	var close = priceClose();
	printf("\ntic [%s] %s ask=%.5f bid=%.5f spread=%.6f",
		strdate("%H:%M:%S.", NOW),
		Asset,
		close,
		close - Spread,
		Spread
	);
}

function run() 
{
	set(TICKS + LOGFILE + PLOTNOW + PRELOAD);
	resf(BarMode, BR_WEEKEND);
	setf(BarMode, BR_FLAT);
	Verbose = 7 + DIAG + ALERT;
	Hedge = 2;

	BarPeriod = 1;
	LookBack = 300;

	asset("AAPL");

	Capital = 10000;

	setf(TradeMode, TR_GTC);

	if (is(INITRUN)) {
		startTime = timer();
	}

	var Close = priceClose();
	var DepthPIPs = 4;
	var TopAsk = Close;
	var TopBid = Close - Spread;
	var LimitAsk = round_up(TopAsk + DepthPIPs * PIP, PIP);
	var LimitBid = round_down(TopBid - DepthPIPs * PIP, PIP);

	if (!is(LOOKBACK)) {
		var Position = brokerCommand(GET_POSITION, Asset);
		printf("\n======> %s bar at %s, limit ask=%.5f top ask=%.5f top bid=%.5f limit bid=%.5f\n  Position %.2f, LotsPool %.2f",
			Asset,
			strdate(HMS, 0),
			LimitAsk,
			TopAsk,
			TopBid,
			LimitBid,
			Position,
			(var)LotsPool
		);
		
		count += 1;
	}

	if (!is(LOOKBACK) && !Quoting) {
		Lots = 1;
		OrderLimit = LimitAsk;
		printf("\nenterShort: OrderLimit=%.5f", OrderLimit);
		enterShort(diagnostics_tmf);

		OrderLimit = LimitBid;
		printf("\nenterLong: OrderLimit=%.5f", OrderLimit);
		enterLong(diagnostics_tmf);

		Quoting = true;
		OrderLimit = 0;
	}
	
	if (count == 3) {
		printf("\n********* cancel all orders *********");
		exitLong("**");
		exitShort("**");
	}

	diagnostics_trades();
}
```

The plugin correctly opens the two limit orders, however on the Zorro side they are immediately considered as filled and the TradeProfit is not 0. 

Note that Zorro introduced a TradeMode flag TR_FILLED flag, which is NOT set here (by default it is NOT set).

Also when the orders are cancelled, they are properly canceled in Alpaca, but Zorro keeps them `pending` instead of canceled. 

It is not clear to me if it is a bug in Zorro or in the plugin. 

Working limit orders is very important and it would be great if that can be made working. Thanks for looking into this.

**Comment by degloff** [comment]
When I debugged the Zorro FIX plugin for FXCM I found that BrokerBuy2 has to set the fill to 0, again despite the output arg is marked as optional. Details here https://github.com/dsec-capital/zorro-fix/blob/07d33ead9c43c1268607debdf7f0e0ec4a873762/zorro_fxcm_fix_plugin/zorro_fxcm_fix_plugin.cpp#L966

I am still not sure how to handle though the case of a partially filled order in the BrokerSell2 function. Do you have any understanding about this?

Let me know if that suggestion solves the issue that I observed when testing the Alpaca plugin.

**Comment by kzhdev** [comment]
I will take a look when the market opens on Monday.

**Comment by degloff** [comment]
Thanks a lot, check what Zorro returns as PnL. It looks to me that the plugin correctly places the order but if it is in the book Zorro assumes it is immediately filled. I had a similar issue when programming the FIX plugin and I solved it by explicitely returning 0 from the BrokerBuy2 function.

**Comment by kzhdev** [comment]
In Alpaca, the script successfully placed the sell limit order, but Alpaca rejected the buy limit order with the following message:

`{"code":40310000,"message":"cannot open a long buy while a short sell order is open"}`. 

This is not what I expected. It looks like Alpaca has a restriction. I posted a message on Alpaca's support channel to find out.

Zorro's TradeIsUnfilled doesn't seem right to me. The log says the sell order is open , but unfilled is no. The TradePriceClose is the current market price, and TradeProfict is just the open PnL.

+++++ 416100002 open sell TradeLots(open)=1.000000 TradeLotsTarget=1.000000 TradePriceOpen=196.350006 TradeProfit=0.280002
tmf [15:07:02.676] id=416100002 sell missed=no pending=no open=yes unfilled=no TradePriceOpen=196.35001 TradePriceClose=195.53000 TradeFill=195.80001 TradeProfit=0.27001
tic [15:07:02.679] AAPL ask=195.53000 bid=195.25000 spread=0.280000

I suggest sending an email to Zorro's support, there might be a bug on TradeIsUnfilled. 

For the brokerBuy2 return, explicitly returning 0 doesn't seem right. Returning 0/1 is for FOK and IOC orders.

**Comment by kzhdev** [comment]
I tried to set the pFill to 0 in the brokerBuy2 function. It doesn't make any difference.

**Comment by kzhdev** [comment]
I checked Zorro manual again. You are right; Zorro treats the limit order as filled. IMO, both TradeIsOpen and TradeUnfilled are wrong.

**Comment by kzhdev** [comment]
The plugin must set pFill to 0 if the order is not filled. After setting pFill to 0, the TradeProfit always prints 0. It looks like Zorro doesn't treat the order as filled anymore. However, TradeIsOpen and TradeIsUnfilled still seem wrong.
