### ISSUE TITLE
Zorro hedging net orders not found

### ISSUE THREAD

**Issue by EwanBSmith** [kzhdev/alpaca_zorro_plugin#13]
It seems that when using Hedge = 5 and NFA, that the "net" orders created by Zorro cannot be found on Alpaca after a restart.

I get the following in the logs after a restart:
```
!order not found for ZORRO_428700001
!order not found for ZORRO_428700002
!order not found for ZORRO_428700003
```

where each of these orders is a netted order for each symbol (the combination of more than one algo trading the same symbol).

**Comment by kzhdev** [comment]
Which Zorro version do you use?

**Comment by EwanBSmith** [comment]
> @EwanBSmith I couldn't reproduce the issue. Do you use limit or market order? Do you use GTC? Did you switched to different account?

Zorro S 2.62.1 - Market orders placed using ORDERTYPE_CLS. Account was the same, just a restart of the Zorro client.

**Comment by kzhdev** [comment]
Which AlpacaPlugin version do you have?

**Comment by EwanBSmith** [comment]
> Which AlpacaPlugin version do you have?

1.3.4

I restarted Zorro just there and it managed to find the trades successfully, so I'm not really sure what happened. I think I had generated a new API key on Alpaca and entered it into Zorro after the restart, even though it did not change which account it was pointing to.

This can be closed.

**Comment by kzhdev** [comment]
@EwanBSmith If you see this again, please add the following code to the strategy. It logs all order details in the alpaca log. You can then verify if the order exists in Alpaca.
                #include <include/AlpacaBrokerCommands.h>
                ....
		brokerCommand(SET_LOG_TYPE, 8);
		brokerCommand(SET_LOG_LEVEL, 4);
