### ISSUE TITLE
"!insufficent subscription(409) error

### ISSUE THREAD

**Issue by foxxcrypto** [kzhdev/alpaca_zorro_plugin#7]
I'm trying to connect zorro with my Alpaca account, but I get the following error message, what is it due to?
"!insufficent subscription(409)
Unable to oprn Alpaca websocket. Prices will be pulled from REST API.
Login failed
request is not authorized
Can't connect

thank. bye

**Comment by kzhdev** [comment]
It sounds like you have a basic market data plan and trying to connect to the pro-market data endpoint. If you have a basic market data plan, try to add '''AlpacaPaidDataPlan = 0''' in your Zorro.ini or ZorroFix.ini

**Comment by foxxcrypto** [comment]
thanks! it works. .but now it gives me a second error 

Login 0 Alpaca...
!Login failed.
!request is not authorized

I used the api key as login and the secret key as password and I double-checked several times if they are correct. Put them in zorro's account file with the following line..

Alpha,Alpaca,0,apikey,secretkey,AssetsSeasonality,USD,0,14,Alpaca.dll

do you have any suggestions?

**Comment by kzhdev** [comment]
Is this a paper account or a live account? If it is a live account, the number before 14 should be 1.
In Zorro.ini, add AlpacaLogLevel = 6. Then look at the Alpaca_<date>_<pid>.log file in Zorro\Log folder. It should give more information.

**Comment by enivant** [comment]
Hello, I'm trying out the alpaca plugin, want to test the paper trading. So connection is working an I wrote a simple zorro-script:

_#include <profile.c>
_#include "include/AlpacaBrokerCommands.h"

function main() 
{
	asset("NVDA");
	enterLong(1);

	string Name;
	Name = "NVDA";
	var Position = brokerCommand(GET_POSITION,Name);
        printf("\n%6.4f %s",Position);
}__

But no stock is ordered, waht I#M doing wrong?
Thanks a lot

**Comment by enivant** [comment]
Hello back, thanks a lot for your quick answer. I follwow your tip and it works. I have not yet tried a strategy that requires a certain lockback period, but I will give it a try. In any case, it would be a very good opportunity to test your strategy live (with paper money).

**Comment by kzhdev** [comment]
I'm glad that helped.
