### ISSUE TITLE
Indices support using polygon

### ISSUE THREAD

**Issue by kristof-troch** [kzhdev/alpaca_zorro_plugin#8]
As alpaca does not have any data support for indices like VIX / VIX3M...I was trying to use the polygon option in the plugin but tht failed as well. 

_Warning 033: no VIX data in INITRUN
!Failed to get lastTrade VIX error: no snapshot found for VIX
Warning 033: no VIX3M data in INITRUN
!Failed to get lastTrade VIX3M error: invalid symbol: VIX3M_

When browsing thru the code I saw the polygon features implemented don't support the indices neither?

Any plans  / option to include these as well?

Thanks

**Comment by kzhdev** [comment]
The polygon market data was implemented early when Alpaca used polygon market data. Since Alpaca no longer supports polygon anymore, I have no plan to expand it.
